apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: amirrze/notification:v2.0.0
        ports:
        - containerPort: 12345
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-local:9092"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 12345
