apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregation
  template:
    metadata:
      labels:
        app: aggregation
    spec:
      containers:
      - name: aggregation
        image: amirrze/aggregation:v1.0.0
        ports:
        - containerPort: 7000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-local:9092"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "7000"
---
apiVersion: v1
kind: Service
metadata:
  name: aggregation-service
spec:
  selector:
    app: aggregation
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
