apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion
        image: amirrze/ingestion:v1.0.0
        ports:
        - containerPort: 8500
        env:
        - name: REDIS_URL
          value: "redis://redis-local-1:6389"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-local-1:9097"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8500"
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  selector:
    app: ingestion
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
